### ISSUE TITLE
Installed on PyPi

### ISSUE THREAD

**Issue by Steven-N-Hart** [cytomine/Cytomine-python-client#14]
I went ahead and made this available on PyPi:
> `pip install cytomine-python-client`

**Comment by nznmol** [comment]
Actually - this repository seems out of date. the [docs for managing software](http://doc.cytomine.be/display/ALGODOC/%5BHOWTO%5D+Manage+software+and+servers+for+administrators#id) have the following python code:

```
from cytomine.models import SoftwareUserRepository
```

but this repo doesn't have a `SoftwareUserRepository` in models... it is present in [the fork](https://github.com/Cytomine-ULiege/Cytomine-python-client) though

I propose making the fork the package represented on pypi, or updating this repo and publishing a new release.
