### ISSUE TITLE
Feature Request: Extract Image Patch

### ISSUE THREAD

**Issue by Steven-N-Hart** [cytomine/Cytomine-python-client#15]
I have found the Python Client to be helpful for extracting annotations, but I can't seem to figure out how I could get the corresponding image for that region.  The Mask file is nice, but I'm looking for the full image.

**Comment by smujiang** [comment]
I think that feature may be in Cytomine-IMS: Image Management System, but it's written with Groovy.
https://github.com/cytomine/Cytomine-IMS
A alternative way is download the whole slide image and extract the ROI you need.

**Comment by Steven-N-Hart** [comment]
Thanks.  The latter is the approach we ended up taking.
