### ISSUE TITLE
Create a more explicit error message when using "with Cytomine"

### ISSUE THREAD

**Issue by geektortoise** [cytomine/Cytomine-python-client#18]
With the new Cytomine python, we write our script into the
    `with Cytomine(host=params.host, public_key=params.public_key, private_key=params.private_key) as cytomine:`
declaration

If we forgot one of these 3 values in the command line, we got the error 
TypeError: encoding without a string argument

This error is not explicit enough

**Comment by waliens** [comment]
Should use: 
```python
with Cytomine.connect_from_cli(sys.argv) as conn:
    # ...
```
