### ISSUE TITLE
Package version does not match release version

### ISSUE THREAD

**Issue by MTHSBGN** [cytomine/Cytomine-python-client#19]
In setup.py, the package version does not match the release version (2.1.1 <> 2.2.0).

https://github.com/cytomine/Cytomine-python-client/blob/83ab8dd9f68d5ee4fdb12bf57c3ade63f5547b74/setup.py#L25

This creates a problem when trying to install requirements for another package that reference the 2.2.0 version.

**Comment by geektortoise** [comment]
Sorry, 

I didn't react to this ticket.
Thank you for the issue, as you have seen, it is fixed now.

Have a nice day !
