### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by pj7801** [cytomine/Cytomine-python-client#21]
As you probably know Python 2.7 is end of support since Jan 2020. Are there any plans to move the client to a Python 3 codebase?
Or it is working today, can you please update the installation documentation, how to make it work?

**Comment by gvincke** [comment]
Dear @pj7801 ,
As mentioned in the official documentation, python3 is definitively the default version to use.
Please follow the instructions detailed here : [https://doc.cytomine.org/Python-client](https://doc.cytomine.org/Python-client?structure=DataScientists).
Best regards,
Grégoire

**Comment by pj7801** [comment]
Thanks Gregorie. Please update README.md with the link to the correct documentation.
Cheers,
Patrik

**Comment by gvincke** [comment]
@pj7801 : Done. 
Thanks to have pointed this out.
