### ISSUE TITLE
Change point(0,0) from bottom left to top left

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/Cytomine-python-client#24]
Hi @geektortoise and Cytomine developers,

I was working with "add_annotation.py" to add a set of bulk coordinates obtained from MATLAB into Cytomine. I'm having a problem here because Cytomine uses bottom left (0,0) and MATLAB uses top left (0,0).  

Most solutions I found were suggesting `plt.gca().invert_xaxis()`, but I want to manipulate the coordinates instead, only for this particular set of images (not changing the whole Cytomine).

Is there any way to do this? Many thanks in advance.

**Comment by waliens** [comment]
Hi,

If you represent your annotations as Shapely polygons, you can use this python function to change the referential (bottom left <-> top left)

```python
from shapely.affinity import affine_transform

def change_referential(polygon, height):
    return affine_transform(polygon, [1, 0, 0, -1, 0, height])
```

Polygon is a shapely polygon and height is the full image height.

Best

**Comment by mizjaggy18** [comment]
Hi there @waliens! Thanks so much, the solution is flawless!
