### ISSUE TITLE
Get term name

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/Cytomine-python-client#25]
Hi Cytomine developers, 

Is there a way to get list of term names and IDs for an ontology or a project created from Cytomine Web-UI? I couldn't find anything related inside the AnnotationCollection().

Please advise, thank you.

**Comment by geektortoise** [comment]
Hello, 

You can fetch the TermCollection by filtering with the ontology or the project id.

https://github.com/cytomine/Cytomine-python-client/blob/master/cytomine/models/ontology.py#L63

I guess a TermCollection().fetch_with_filter("project", params.id_project)
should be ok.
In each Term, you will have the "id" and "name" attributes.

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

Thank you so much for your kind assistance, I was working on something else and just tried this, it worked perfectly! I shall close this issue/question now. Thank you.
