### ISSUE TITLE
Add software to Cytomine Web-UI

### ISSUE THREAD

**Issue by mizjaggy18** [cytomine/Cytomine-python-client#26]
Hi @geektortoise and Cytomine developers,

I've been trying to add my own software by following the steps in [here](https://doc.cytomine.org/Add-an-external-software-to-Cytomine), but no newly added algorithm appears in my Cytomine Web-UI. The steps I did were:

Yesterday:
1. git clone https://github.com/cytomine/S_python_software_example.git into /Cytomine-python-client/examples/ folder
2. Modify the codes tailored to my codes
3. sudo docker build -t mizjaggy18/s_python_classifypncell:v1.0.0-beta .
4. Upload the files to github (using browser) and assign tag
4. sudo docker login
    sudo docker push mizjaggy18/s_python_classifypncell:v1.0.0-beta
5. Add Trusted Sources of my username for both git and docker, with prefix "S_"

No success :(

Today: 
1. Copy the existing "S_python_software_example" folder and change the "example" to "test", move it to outside of /Cytomine-python-client folder
2. sudo docker login
    sudo docker build -t mizjaggy18/s_python_software_test:v1.0 .
    sudo docker push mizjaggy18/s_python_software_test:v1.0
3. Create a new repo named "S_Python_Software_Test" in github (using browser)
4. git config user.email "my email"
    git config user.name "mizjaggy18"
    echo "# S_Python_Software_Test" >> README.md
    git init
    git add .
    git commit -m "first commit"
    git branch -M main
    git remote add origin https://github.com/mizjaggy18/S_Python_Software_Test.git
    git push origin +main

Still no success :(

Is there anything I missed? This is for localhost-core, not the public URL yet. Please advise, thank you very much.

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

I tried to upload the software using "upload_software.py" in the example folder. The input as below:

      python3 upload_software.py --cytomine_host "http://localhost-core" --cytomine_public_key "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" --cytomine_private_key "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  --software_name "Python_ClassifyPNCell" --filepath "/Cytomine-python-client/examples/S_python_classifyPNcell.zip"

The zip file contains all related files: descriptor.json, Dockerfile and run.py

However I got the following error:
[2021-05-05 16:28:11,816][INFO] [GET] [currentuser] CURRENT USER - 61 : admin | 200 OK
[2021-05-05 16:28:13,510][ERROR] Error during file uploading to software/upload

Please advise, thank you.

**Comment by geektortoise** [comment]
Hello.
Sorry for the delay.

For your first question : it is the software_router component that should fetch your GitHub.
Can you check the logs of the software_router : `sudo docker logs software_router`
As it can be long, you can filter it with `sudo docker logs software_router | grep mizjaggy18`
You can also check if the singularity images of the softwares have been created :
```
sudo docker exec -it  software_router bash
ls /data/softwares/images/
```

I will add your repo in my localhost to check it.

I see that the docker repository still reference the cytomine one here but I will check it has an impact.
https://github.com/mizjaggy18/S_Python_Software_Test/blob/main/descriptor.json#L5


For your second error, does the core container logs give you more information ? :(

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

Thank you for your reply. 

**Related to Question 1:**
I think software_router container is not running, I'm not sure why.

This is the output of `sudo docker ps`:
![image](https://user-images.githubusercontent.com/77017051/117251795-b40ca180-ae77-11eb-8843-41eb2ddecad4.png)

I don't see 'software_router' there.. Hence, `sudo docker logs software_router` returns:

2021-04-19 07:46:30 INFO  Main:45 - PATH : /usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin
2021-04-19 07:46:32 INFO  HttpClient:125 - Connection to http://localhost-core/api/user/current.json
Exception in thread "main" 504 
	at be.cytomine.client.CytomineConnection.analyzeCode(CytomineConnection.java:116)
	at be.cytomine.client.CytomineConnection.doRequest(CytomineConnection.java:163)
	at be.cytomine.client.CytomineConnection.doGet(CytomineConnection.java:171)
	at be.cytomine.client.models.Model.fetch(Model.java:116)
	at be.cytomine.client.models.Model.fetch(Model.java:112)
	at be.cytomine.client.CytomineConnection.getCurrentUser(CytomineConnection.java:106)
	at be.cytomine.client.CytomineConnection.getCurrentUser(CytomineConnection.java:99)
	at be.cytomine.client.Cytomine.getCurrentUser(Cytomine.java:438)
	at be.cytomine.client.Cytomine$getCurrentUser$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
	at be.cytomine.software.consumer.Main.main(Main.groovy:79)

There is also nothing inside /data/softwares/images/ folder. /images folder has not yet been created, only /code folder is available inside /data/softwares. 

**Related to Question 2:**
I just checked `sudo docker logs core` after re-running the 'upload_software.py' command, and the output is:

06-05-2021 06:41:10,519  INFO RequestFilters - restUser.showCurrent: user:61
06-05-2021 06:41:10,570  INFO RequestFilters - restUser.showCurrent Request took 50ms
06-05-2021 06:41:10,784  INFO RequestFilters - restSoftware.upload: user:61
06-05-2021 06:41:10,790  INFO RestSoftwareController - Upload software source
06-05-2021 06:41:10,880  INFO ModelService - Command class be.cytomine.command.AddCommand with flag false
06-05-2021 06:41:11,031 ERROR RestSoftwareController - add error:Software Python_ClassifyPNCell already exist!
06-05-2021 06:41:11,034 ERROR RestSoftwareController - be.cytomine.Exception.AlreadyExistException
06-05-2021 06:41:11,045  INFO RequestFilters - restSoftware.upload Request took 317ms
06-05-2021 06:41:12,533  INFO LogoutEventListener - session 91C1A3D782B337D3E45459AB4A2DEA5C destroyed !

Since the error is 'already exist!', I re-check the Cytomine web-UI. There is still no new software added. Until I switched off 'ONLY LAST RELEASES' and 'ONLY RUNNABLE ALGORITHMS' filters. There are three new algorithms added on 19 April, but how to make it runnable and with release using 'upload_software.py'? 

![image](https://user-images.githubusercontent.com/77017051/117255153-e6200280-ae7b-11eb-9f4f-005951a8dfc0.png)


I look forward to getting your reply. Thank you for your time and advice.

**Comment by geektortoise** [comment]
Hello, when adding your username, the software_router fetched your "test" software. :-) 

![image](https://user-images.githubusercontent.com/8018298/117653105-4f618780-b194-11eb-9b2a-4252cce885d3.png)

![image](https://user-images.githubusercontent.com/8018298/117653153-5ab4b300-b194-11eb-9df9-246286beb4c6.png)

The 504 means that a timeout occured. Does a 
`bash restart.sh` 
fix the problem ?

PS : note that you can update the core version to 3.0.3, ims to 1.2.6 and web_ui to 1.2.2 :-)

**Comment by mizjaggy18** [comment]
Hi @geektortoise,

After trying out so many ways, and with the new documentation in [here](https://doc.cytomine.org/dev-guide/algorithms/write-app#requirements) and [here](https://doc.cytomine.org/dev-guide/algorithms/release-app#make-a-new-release), the algorithm has finally appeared in my localhost Cytomine! Yeayy! 

Other than naming rules mistake in my previous "descriptor.json" (and thankfully it has now been clearly illustrated in the "big picture of a Cytomine app release" :+1:), the main mistake causing the error is a comma ',' after the last parameter declaration, before the closing square bracket ']'. This also appears in [JSON descriptor reference Complete example](https://doc.cytomine.org/dev-guide/algorithms/descriptor-reference#complete-example), maybe because we're copy-pasting from the initial parameters. But looking at the `sudo docker logs software_router` really helps a lot. Thanks so much! 

However I still have several questions:
1. Do I need to create a new release after each change in order for Docker to fetch/autobuild the change from Github?
2. If the uri in "descriptor.json" is `/api/ontology/$currentOntology$/term.json`, what is the suitable `uri-print-attribute`? 


> PS : note that you can update the core version to 3.0.3, ims to 1.2.6 and web_ui to 1.2.2 :-)

Sure, I will update them! Thank you :)

**Comment by geektortoise** [comment]
Hello, 

Thanks for the feedback.
In order to improve our documentation (with a FAQ or "Recurrent errors" page), do you still have the logs that help you to identify the comma ?

For the questions :
1. Currently, yes. It could lead to a huge number of "patch" versions so for our developments, we often test it as an "external script" and release a version when our local tests succeed.
2. The suitable attribute is the name. :-) See this example : https://github.com/cytomine/S_CellDetect_Stardist_HE_ROI/blob/master/descriptor.json#L85

**Comment by geektortoise** [comment]
Thanks to @urubens for the documentation about the software that help you !

**Comment by mizjaggy18** [comment]
Hi @geektortoise, @urubens and Cytomine developers,

You guys really are awesome!

Here's the logs from `software_router` related to the comma error:

> 2021-05-18 08:01:15 INFO  CommunicationThread:63 - [Communication] Received message: {"requestType":"refreshRepository","id":46142,"username":"mizjaggy18"}
> 2021-05-18 08:01:15 INFO  CommunicationThread:117 - [Communication] Refresh software user repository: mizjaggy18
> 2021-05-18 08:01:15 INFO  RepositoryManagerThread:57 - Refreshing the repository manager mizjaggy18 !
> 2021-05-18 08:01:15 INFO  SoftwareManager:48 - Refresh repository manager SoftwareManager mizjaggy18 / mizjaggy18 with prefixes: [S_]
> 2021-05-18 08:01:17 INFO  SoftwareManager:50 - [s_classify_pn_cells, s_python_software_test]
> 2021-05-18 08:01:17 INFO  SoftwareManager:54 - Repository to refresh : s_classify_pn_cells - Last version installed is null
> 2021-05-18 08:01:17 INFO  SoftwareManager:56 - tags : [v0.1.7, v0.1.6]
> 2021-05-18 08:01:17 INFO  SoftwareManager:65 - -> Add the software [s_classify_pn_cells] - v0.1.7
> groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
> 
> The current character read is ']' with an int value of 93
> Unable to determine the current character, it is not a string, number, array, or object
> line number 79
> index number 2326
>   ],
> ..^
> 	at groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:206)
> 	at groovy.json.internal.JsonParserCharArray.decodeJsonArray(JsonParserCharArray.java:326)
> 	at groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:182)
> 	at groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:132)
> 	at groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:186)
> 	at groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:157)
> 	at groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:45)
> 	at groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:385)
> 	at groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:124)
> 	at groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:149)
> 	at groovy.json.JsonSlurper.parseFile(JsonSlurper.java:362)
> 	at groovy.json.JsonSlurper.parse(JsonSlurper.java:345)
> 	at groovy.json.JsonSlurper$parse$0.call(Unknown Source)
> 	at be.cytomine.software.boutiques.Interpreter.<init>(Interpreter.groovy:39)
> 	at sun.reflect.GeneratedConstructorAccessor43.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
> 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
> 	at be.cytomine.software.management.AbstractSoftwareManager.installSoftware(AbstractSoftwareManager.groovy:39)
> 	at be.cytomine.software.management.AbstractSoftwareManager$installSoftware.call(Unknown Source)
> 	at be.cytomine.software.repository.SoftwareManager$_updateSoftware_closure1.doCall(SoftwareManager.groovy:71)
> 	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
> 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
> 	at groovy.lang.Closure.call(Closure.java:423)
> 	at groovy.lang.Closure.call(Closure.java:439)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2027)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2012)
> 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2053)
> 	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
> 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
> 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
> 	at be.cytomine.software.repository.SoftwareManager.updateSoftware(SoftwareManager.groovy:51)
> 	at be.cytomine.software.repository.SoftwareManager$updateSoftware.call(Unknown Source)
> 	at be.cytomine.software.repository.threads.RepositoryManagerThread.refresh(RepositoryManagerThread.groovy:59)
> 	at be.cytomine.software.repository.threads.RepositoryManagerThread$refresh.call(Unknown Source)
> 	at be.cytomine.software.consumer.threads.CommunicationThread.run(CommunicationThread.groovy:118)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 2021-05-18 08:01:18 INFO  SoftwareManager:88 - --> Unknown exception occurred : null
> 2021-05-18 08:01:18 INFO  SoftwareManager:54 - Repository to refresh : s_python_software_test - Last version installed is v1.0
> 2021-05-18 08:01:19 INFO  SoftwareManager:56 - tags : [v1.0]
> 2021-05-18 08:01:19 INFO  SoftwareManager:92 - -> Last version is already installed. Skip.
> 2021-05-18 08:01:19 INFO  SoftwareManager:98 - Finished to refresh.


Thank you, please feel free to close this thread. I think I'm good for now :)

**Comment by fukexue** [comment]
When I upload the software, the following error is displayed. Do you have any suggestions?
`15-01-2025 03:59:15,881  INFO RequestFilters - restSoftware.upload Request took 4ms
15-01-2025 03:59:35,976  INFO RequestFilters - command.listDelete: 15-01-2025 03:59:35,979  INFO RequestFilters - command.listDelete Request took 4ms
15-01-2025 03:59:43,529  INFO RequestFilters - restUser.showCurrent: user:61
15-01-2025 03:59:43,531  INFO RequestFilters - restUser.showCurrent Request took 2ms
15-01-2025 03:59:43,542  INFO RequestFilters - restSoftware.upload: user:61
15-01-2025 03:59:43,542  INFO RestSoftwareController - Upload software source
15-01-2025 03:59:43,543  INFO ModelService - Command class be.cytomine.command.AddCommand with flag false
15-01-2025 03:59:43,577 ERROR GrailsExceptionResolver - FileNotFoundException occurred when processing request: [POST] /api/software/upload
/data/softwares/code/262676/S_testapp.zip (No such file or directory). Stacktrace follows:
java.io.FileNotFoundException: /data/softwares/code/262676/S_testapp.zip (No such file or directory)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.commons.fileupload.disk.DiskFileItem.write(DiskFileItem.java:417)
	at be.cytomine.api.processing.RestSoftwareController.upload(RestSoftwareController.groovy:161)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:203)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:181)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at cytomine.web.APIAuthentificationFilters.doFilter(APIAuthentificationFilters.groovy:46)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
