### ISSUE TITLE
Fix tests 

### ISSUE THREAD

**Issue by geektortoise** [cytomine/Cytomine-python-client#41]
I created a branch "fix_tests" with first commits to fix tests after integration from ULiège.

There is a lot of room for improvements :-)
- Some ids are hardcoded in [tests/conftest.py](https://github.com/cytomine/Cytomine-python-client/commit/4a80417eb95492ec0ddfda203271738dd4ec1dcd#diff-e2040ef9df645736ab40a5bc4185b377ced19d77cc889d83094bfb8569442b84) and in https://github.com/cytomine/Cytomine-python-client/commit/4a80417eb95492ec0ddfda203271738dd4ec1dcd#diff-52f14516559f7a4a8188f09e86effc66b8bc6a61dee05b89d4695723d57c271aR58 due to the fact that ImageServer is not defined in the client. Replace it with a ImageServer.list().get(0)
- In [tests/conftest.py](https://github.com/cytomine/Cytomine-python-client/commit/4a80417eb95492ec0ddfda203271738dd4ec1dcd#diff-e2040ef9df645736ab40a5bc4185b377ced19d77cc889d83094bfb8569442b84), id_storage are hardcoded, replace it with the current_storage of the current user. You can find an inspiration here : https://github.com/cytomine/Cytomine-java-client/blob/master/src/main/java/be/cytomine/client/models/Storage.java#L32
- In test_image.py, there is no test for abstract_slice or slice_instance. I guess a computer scientist using the python client can want to list the sliceinstances of an imageinstance. Please create them.
- The imagegroup test are failing. I think they are related to the "old" image group concept, skip or remove the tests.

**Comment by chlmarchal** [comment]
The modifications have been made :)
