### ISSUE TITLE
how to delete point annotation from a list 

### ISSUE THREAD

**Issue by aled88** [cytomine/Cytomine-python-client#9]
Hi i have a list of coordinate that i create but with a wrong term.

How do i delete the point from the list or update it with correct term.

Right now the point is mixed with other correct term.

I used the create_annotation.py to create the POINT annotation with terms.
delete_annotations.py will delete all of term but i want to delete by coordinate x,y from my list.

**Comment by geektortoise** [comment]
I don't understand.
If you know the id of the "wrong annotation", you can delete it with this function
https://github.com/cytomine/Cytomine-python-client/blob/master/client/cytomine/cytomine.py#L622

We can't currently delete annotations with the coordinates.

**Comment by aled88** [comment]
> We can't currently delete annotations with the coordinates.

Ok guess i need to use get annotations to grab its id and coordinate. Then compare it with my correct list under if statement to delete the wrong term in a loop. Thank you.
